//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NP.DAL.Security
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.UserInformations = new HashSet<UserInformation>();
        }
    
        public int Id { get; set; }
        public string RoleName { get; set; }
        public string RoleResponsibility { get; set; }
    
        public virtual ICollection<UserInformation> UserInformations { get; set; }
    }
}
